# S02 T04: Pràctica amb programació numèrica

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [5]:
import numpy as np
import statistics as stat
def resumArray(a):
    print("Mitjana",np.median(a) )
    print("Mitja aritmètica",np.mean(a))
    print("Moda",stat.mode(a) )
    print("Desviació estandar",np.std(a))

x = input("Escriu un array de números: ")
b = x.split()
res = [int(i) for i in b]
c = np.array(res)
resumArray(c)


Escriu un array de números: 6 9 14 24 2 8 9
Mitjana 9.0
Mitja aritmètica 10.285714285714286
Moda 9
Desviació estandar 6.518419740885619


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [46]:
def randomMatrix(x):
    a = np.random.randint(100, size=(x,x))
    print(a)

x = input("Escriu el tamany de la matriu: ")
b = int(x)
randomMatrix(b)

Escriu el tamany de la matriu: 4
[[43 78 92 97]
 [ 8 36 62 67]
 [ 1 87 76 31]
 [28 61  3 77]]


### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [125]:
a = np.array([
    [1, 25, 7, 13, 9],
    [5, 8, 27, 4, 10],
    [2, 5, 6, 14, 7],
    [4, 5, 23, 12, 9],
    [9, 2, 16, 3, 11]])
i = 0
s = 0
r = 0
for i in range(len(a)):
    for j in range(len(a[i])):
            s += a[i][j]
            r += a[j][i]
    print("suma fila ",j,": ", s)
    print("suma columna ",j,": ", r)
        



#x = input("Escriu el tamany de la matriu: ")
#b = int(x) 

suma fila  4 :  55
suma columna  4 :  21
suma fila  4 :  109
suma columna  4 :  66
suma fila  4 :  143
suma columna  4 :  145
suma fila  4 :  196
suma columna  4 :  191
suma fila  4 :  237
suma columna  4 :  237


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [59]:
a = np.array([
    [1, 25, 7, 13, 9],
    [5, 8, 27, 4, 10],
    [2, 5, 6, 14, 7],
    [4, 5, 23, 12, 9],
    [9, 2, 16, 3, 11]])

def coefCorr(a):
    i = 0
    for i in range(len(a)):
        columna = a[:,i]
        fila = a[i,:]
       # print(columna, " ", fila)
        print(np.corrcoef (columna, fila))
        
coefCorr(a)

[[1.         0.37692803]
 [0.37692803 1.        ]]
[[ 1.         -0.35430044]
 [-0.35430044  1.        ]]
[[1.         0.49199468]
 [0.49199468 1.        ]]
[[1.         0.48151166]
 [0.48151166 1.        ]]
[[ 1.         -0.47035821]
 [-0.47035821  1.        ]]
