# S02 T04: Pràctica amb programació numèrica

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
import numpy as np
import statistics as stat
def resumArray(a):
    print("Mitjana",np.median(a) )
    print("Mitja aritmètica",np.mean(a))
    print("Moda",stat.mode(a) )
    print("Desviació estandar",np.std(a))

x = input("Escriu un array de números: ")
b = x.split()
res = [int(i) for i in b]
c = np.array(res)
resumArray(c)


Escriu un array de números: 2 4 6 8 12 16 4 36
Mitjana 7.0
Mitja aritmètica 11.0
Moda 4
Desviació estandar 10.3923048454


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [17]:
def randomMatrix(x):
    a = np.random.randint(100, size=(x,x))
    print(a)

x = input("Escriu el tamany de la matriu: ")
b = int(x)
randomMatrix(b)

Escriu el tamany de la matriu: 8
[[98 60 66 92 17 10 42 88]
 [29 23 59 61 28 86 91 81]
 [46 99 44 60 14 95 34 23]
 [ 4 87 32 32 81 71 51 13]
 [96 70 33  9 11 50 46 41]
 [ 6 35 96 20 96 86 80  1]
 [89 27 74 39 86  0 12 89]
 [ 4 52 76 13  1 45 61 72]]


### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [16]:
a = np.array([
    [1, 25, 7, 13, 9],
    [5, 8, 27, 4, 10],
    [2, 5, 6, 14, 7],
    [4, 5, 23, 12, 9],
    [9, 2, 16, 3, 11]])

def calcRowColumn(a):
    i = 0
    for i in range(len(a)):
        s = 0
        r = 0
        for j in range(len(a[i])):
                s += a[i][j]
                r += a[j][i]
        print("suma fila ",i+1,": ", s)
        print("suma columna ",i+1,": ", r)
        
calcRowColumn(a)

suma fila  1 :  55
suma columna  1 :  21
suma fila  2 :  54
suma columna  2 :  45
suma fila  3 :  34
suma columna  3 :  79
suma fila  4 :  53
suma columna  4 :  46
suma fila  5 :  41
suma columna  5 :  46


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [59]:
a = np.array([
    [1, 25, 7, 13, 9],
    [5, 8, 27, 4, 10],
    [2, 5, 6, 14, 7],
    [4, 5, 23, 12, 9],
    [9, 2, 16, 3, 11]])

def coefCorr(a):
    i = 0
    for i in range(len(a)):
        columna = a[:,i]
        fila = a[i,:]
       # print(columna, " ", fila)
        print(np.corrcoef (columna, fila))
        
coefCorr(a)

[[1.         0.37692803]
 [0.37692803 1.        ]]
[[ 1.         -0.35430044]
 [-0.35430044  1.        ]]
[[1.         0.49199468]
 [0.49199468 1.        ]]
[[1.         0.48151166]
 [0.48151166 1.        ]]
[[ 1.         -0.47035821]
 [-0.47035821  1.        ]]
